CREATE TABLE IF NOT EXISTS FORM2.ARBITR
(
  ID                        SERIAL NOT NULL
    CONSTRAINT ARBITR_PKEY
    PRIMARY KEY,
  USER_ID                   INTEGER,
  THE_SRO_ID                VARCHAR(1024),
  ARBITR_INN_NUMBER         VARCHAR(255),
  ARBITR_SNILS_NUMBER       VARCHAR(255),
  ARBITR_SURNAME            VARCHAR(512),
  ARBITR_NAME               VARCHAR(512),
  ARBITR_SECONDNAME         VARCHAR(512),
  ARBITR_EFRSB_REG_NUMBER   VARCHAR(255),
  ARBITR_ROSREESTR_REG_DATE TIMESTAMP,
  ARBITR_SRO_ENTRY_DATE     TIMESTAMP,
  ARBITR_EFRSB_URL          VARCHAR(512),
  IS_ARBITR_IN_THE_SRO      BOOLEAN DEFAULT FALSE,
  IS_ARBITR_ACTIVE          BOOLEAN DEFAULT FALSE
);
